language: node_js
node_js:
  - "6.0.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - git
before_script:
  - npm install -g gulp
  - npm install
  - git clone http://github.com/datokrat/abnfjs.git
  - git clone http://github.com/disco-network/rdfstore-js.git
  - npm --production --prefix ./abnfjs install ./abnfjs
  - npm --production --prefix ./rdfstore-js install ./rdfstore-js
script: gulp specs
sudo: false
